### PR TITLE
add option to allow HTTP whitelisting

### PR DESCRIPTION
**Pull request by vad**

### CODE REVIEW

**Comment by do3cc** [comment]
What is needed for this to get merged?

**Comment by saily** [comment]
any chance to get this merged after one year of review ;-)

**Comment by rob-b** [comment]
@do3cc @saily To be honest I don't ever use this plugin. I've added you both as collaborators so feel free to merge any PRs you need. I'll look into the process of transferring ownership on pypi too so that you can get releases out

**Comment by rob-b** [comment]
So it turns out I just add either of you guys as an owner on pypi so let me know your usernames on there and I can grant you access

**Comment by vad** [comment]
Since I'm the author of the commits, can I get access too? We use this in production projects. I'm Davide.Setti on PyPi. Thank you

**Comment by rob-b** [comment]
@vad done

**Comment by vad** [comment]
@rob-b thanks!

**Comment by saily** [comment]
i'm saily on pypi

**Comment by rob-b** [comment]
Added saily on pypi too

**Comment by milind-shakya-sp** [comment]
any chance this change is pushed to pypi. Looks like the latest is still 0.2.0 which does not have support for whitelisting.

**Pull request merged**
